/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookingsystem;
import static bookingsystem.logInGUI.roomList;
import static java.lang.Integer.parseInt;


/**
 *
 * @author finso
 */
public class roomBookingMenu extends javax.swing.JFrame {


    /**
     * Creates new form roomBookingMenu
     */
    public roomBookingMenu() {
        initComponents();
        errorMessageLabel.setVisible(false);
    }
    public static void createRooms(){

        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        refreshmentsBox = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        timeFromBox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        timeToBox = new javax.swing.JComboBox<>();
        roomNumBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        roomCapLabel = new javax.swing.JLabel();
        errorMessageLabel = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        resourcesNeededTextField = new javax.swing.JTextField();

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Book rooms");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Room num:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Timeslots:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Refreshments:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Resources needed:");

        refreshmentsBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshmentsBoxActionPerformed(evt);
            }
        });

        jLabel3.setText("From");

        timeFromBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "9", "10", "11", "12", "13", "14", "15", "16", "17" }));
        timeFromBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeFromBoxActionPerformed(evt);
            }
        });

        jLabel7.setText("to");

        timeToBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "9", "10", "11", "12", "13", "14", "15", "16", "17" }));

        roomNumBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "1", "2", "3", "4", "5" }));
        roomNumBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomNumBoxActionPerformed(evt);
            }
        });

        jLabel8.setText("This room has a capacity of:");

        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel10.setText("Note: Room 4 is the only room with disabled access.");

        roomCapLabel.setText("N/A");

        errorMessageLabel.setForeground(new java.awt.Color(255, 0, 0));
        errorMessageLabel.setText("You must enter a room number");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel20.setText("Please list resources with a comma inbetween each item");

        resourcesNeededTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resourcesNeededTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(refreshmentsBox))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(roomNumBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(roomCapLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(timeFromBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(timeToBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(resourcesNeededTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(33, 33, 33))))
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(errorMessageLabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(1, 1, 1)
                .addComponent(errorMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(roomNumBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(roomCapLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(timeFromBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(timeToBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(resourcesNeededTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(refreshmentsBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
    this.dispose();
    mainMenu mm = new mainMenu();
    mm.setVisible(true);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void timeFromBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeFromBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeFromBoxActionPerformed

    private void refreshmentsBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshmentsBoxActionPerformed

    }//GEN-LAST:event_refreshmentsBoxActionPerformed

    private void roomNumBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomNumBoxActionPerformed
       String temp = roomNumBox.getSelectedItem().toString();
    int selectedRoomNum = parseInt(temp);
    if (temp==" "){
        errorMessageLabel.setVisible(true);
    }
    switch(selectedRoomNum){
        case 1:
            roomCapLabel.setText("2");
            break;
        case 2:
            roomCapLabel.setText("4");
            break;
        case 3:
            roomCapLabel.setText("8");
            break;
        case 4:
            roomCapLabel.setText("15");
            break;
        case 5:
            roomCapLabel.setText("50");
            break;
    }
       
    }//GEN-LAST:event_roomNumBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String temp = roomNumBox.getSelectedItem().toString();
    int selectedRoomNum = parseInt(temp);
    if (temp==" "){
        errorMessageLabel.setVisible(true);
    }    
    switch(selectedRoomNum){
        case 1:
            int[] R1timeSlots = {9,10,11,12,13,14,15,16,17};
            int R1timeFrom = (Integer)timeFromBox.getSelectedItem();
            int R1timeTo = (Integer)timeFromBox.getSelectedItem();
            int[] R1occupiedTimeSlots = {R1timeFrom};
            for (int i = 1; i < (R1timeTo-R1timeFrom); i++) {
                R1occupiedTimeSlots[i] = R1timeFrom+i;
            }
            boolean R1refreshments = refreshmentsBox.isSelected();
            String R1ResourcesNeeded = resourcesNeededTextField.getText();
            rooms Room_1 = new rooms(1,2,true,R1refreshments,false,R1ResourcesNeeded,R1timeSlots,R1occupiedTimeSlots);
            roomList.set(0,Room_1);
            break;
        case 2:
            
            int[] R2timeSlots = {9,10,11,12,13,14,15,16,17};
            int R2timeFrom = (Integer) timeFromBox.getSelectedItem();
            int R2timeTo = (Integer) timeFromBox.getSelectedItem();
            int[] R2occupiedTimeSlots = {R2timeFrom};
            for (int i = 1; i < (R2timeTo-R2timeFrom); i++) {
                R2occupiedTimeSlots[i] = R2timeFrom+i;
            }
            boolean R2refreshments = refreshmentsBox.isSelected();
            String R2ResourcesNeeded = resourcesNeededTextField.getText();
            rooms Room_2 = new rooms(2,4,true,R2refreshments,false,R2ResourcesNeeded,R2timeSlots,R2occupiedTimeSlots);
            roomList.set(1,Room_2);
            break;
        case 3:
            int[] R3timeSlots = {9,10,11,12,13,14,15,16,17};
            int R3timeFrom = (Integer) timeFromBox.getSelectedItem();
            int R3timeTo = (Integer) timeFromBox.getSelectedItem();
            int[] R3occupiedTimeSlots = {R3timeFrom};
            for (int i = 1; i < (R3timeTo-R3timeFrom); i++) {
                R3occupiedTimeSlots[i] = R3timeFrom+i;
            }
            boolean R3refreshments = refreshmentsBox.isSelected();
            String R3ResourcesNeeded = resourcesNeededTextField.getText();
            rooms Room_3 = new rooms(3,8,true,R3refreshments,false,R3ResourcesNeeded,R3timeSlots,R3occupiedTimeSlots);            
            roomList.set(2,Room_3);
            break;
        case 4:
            int[] R4timeSlots = {9,10,11,12,13,14,15,16,17};
            int R4timeFrom = (Integer) timeFromBox.getSelectedItem();
            int R4timeTo = (Integer) timeFromBox.getSelectedItem();
            int[] R4occupiedTimeSlots = {R4timeFrom};
            for (int i = 1; i < (R4timeTo-R4timeFrom); i++) {
                R4occupiedTimeSlots[i] = R4timeFrom+i;
            }
            boolean R4refreshments = refreshmentsBox.isSelected();
            String R4ResourcesNeeded = resourcesNeededTextField.getText();
            rooms Room_4 = new rooms(4,15,true,R4refreshments,true,R4ResourcesNeeded,R4timeSlots,R4occupiedTimeSlots);             
            roomList.set(3,Room_4);
            break;
        case 5:
            int[] R5timeSlots = {9,10,11,12,13,14,15,16,17};
            int R5timeFrom = (Integer) timeFromBox.getSelectedItem();
            int R5timeTo = (Integer) timeFromBox.getSelectedItem();
            int[] R5occupiedTimeSlots = {R5timeFrom};
            for (int i = 1; i < (R5timeTo-R5timeFrom); i++) {
                R5occupiedTimeSlots[i] = R5timeFrom+i;
            }
            boolean R5refreshments = refreshmentsBox.isSelected();
            String R5ResourcesNeeded = resourcesNeededTextField.getText();
            rooms Room_5 = new rooms(5,2,true,R5refreshments,false,R5ResourcesNeeded,R5timeSlots,R5occupiedTimeSlots);             
            roomList.set(4,Room_5);
            break;
    }//GEN-LAST:event_jButton1ActionPerformed
    }
    private void resourcesNeededTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resourcesNeededTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resourcesNeededTextFieldActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(roomBookingMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(roomBookingMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(roomBookingMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(roomBookingMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new roomBookingMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel errorMessageLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JCheckBox refreshmentsBox;
    private javax.swing.JTextField resourcesNeededTextField;
    private javax.swing.JLabel roomCapLabel;
    private javax.swing.JComboBox<String> roomNumBox;
    private javax.swing.JComboBox<String> timeFromBox;
    private javax.swing.JComboBox<String> timeToBox;
    // End of variables declaration//GEN-END:variables
}
